config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
    as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  root 'interns#index'
  resources :interns do
    collection do
      get 'overview'
      get 'information'
    end
  end

  get 'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  #match "*path" => "application#handle_404", via: :all
  
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model
 
  attr_accessor :name, :email, :message
 
  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/intern.rb
class Intern < ActiveRecord::Base

attachment :company_image, type: :image

acts_as_taggable_on :labels

acts_as_taggable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  #rescue_from Exception, with: :handle_500 unless Rails.env.development?
  #rescue_from ActionController::RoutingError, with: :handle_404 unless Rails.env.development?
  #rescue_from ActiveRecord::RecordNotFound,   with: :handle_404 unless Rails.env.development?

  def handle_500(exception = nil)
    logger.info "Rendering 500 with exception: #{exception.message}" if exception

    if request.xhr?
      # Ajaxのための処理
      render json: { error: '500 error' }, status: 500
    else
      render template: 'errors/error_500', status: 500, layout: 'application', content_type: 'text/html'
    end
  end

  def handle_404(exception = nil)
    logger.info "Rendering 404 with exception: #{exception.message}" if exception

    if request.xhr?
      # Ajaxのための処理
      render json: { error: '404 error' }, status: 404
    else
      render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
    end
  end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end
 
  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(params[:inquiry])
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end
 
  def thanks
    # メール送信
    @inquiry = Inquiry.new(params[:inquiry])
    InquiryMailer.received_email(@inquiry).deliver
 
    # 完了画面を表示
    render :action => 'thanks'
  end
end

app/controllers/interns_controller.rb
class InternsController < ApplicationController
  before_action :set_intern, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!, only: [:new, :edit, :update, :destroy]
  # GET /interns
  # GET /interns.json
  def index
    @interns = Intern.all
    #@intern_short = 
  end

  # GET /interns/1
  # GET /interns/1.json
  def show
  end

  # GET /interns/new
  def new
    @intern = Intern.new
  end

  # GET /interns/1/edit
  def edit
  end

  # POST /interns
  # POST /interns.json
  def create
    @intern = Intern.new(intern_params)

    respond_to do |format|
      if @intern.save
        format.html { redirect_to @intern, notice: 'Intern was successfully created.' }
        format.json { render :show, status: :created, location: @intern }
      else
        format.html { render :new }
        format.json { render json: @intern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interns/1
  # PATCH/PUT /interns/1.json
  def update
    respond_to do |format|
      if @intern.update(intern_params)
        format.html { redirect_to @intern, notice: 'Intern was successfully updated.' }
        format.json { render :show, status: :ok, location: @intern }
      else
        format.html { render :edit }
        format.json { render json: @intern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interns/1
  # DELETE /interns/1.json
  def destroy
    @intern.destroy
    respond_to do |format|
      format.html { redirect_to interns_url, notice: 'Intern was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def overview
    @interns = Intern.where(intern_type: 1)
  end

  def information
    @tags = ActsAsTaggableOn::Tag.most_used(6)
    @interns = Intern.where.not(intern_type: 1)
    
    if params[:tag].blank? then
    else
      @interns = @interns.tagged_with(params[:tag])
    end

    
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intern
      @intern = Intern.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def intern_params
      params.require(:intern).permit(:title, :context, :start_time, :end_time, :location, :owner,:timeschedule,:deadline,:baggage,:intern_type,:intern_span, :company_image,:remove_company_image, :tag_list)
    end
end

app/controllers/statics_view_controller.rb
class StaticsViewController < ApplicationController
	
	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interns_helper.rb
module InternsHelper
end

app/helpers/statics_view_helper.rb
module StaticsViewHelper
end

app/views/inquiry/confirm.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
 
<%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
  <table class="table">
    <tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :name %>
        <%= @inquiry.name %>
      </td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @inquiry.email %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :message %>
        <%= simple_format(@inquiry.message) %>
      </td>
    </tr>
  </table>
  <%= f.submit '送信', :class => 'btn btn-primary' %>
<% end %>

app/views/inquiry/index.html.erb
<%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
  <div class="page-header">
    <h1>お問い合わせ</h1>
  </div>
 
  <% if @inquiry.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <strong>入力内容にエラーがあります</strong>
      <ul>
        <% @inquiry.errors.each do |attr, msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <table class="table">
    <tr>
      <th>名前<span class="text-danger">（必須）</span></th>
      <td><%= f.text_field :name ,:style=>"width:80%; box-sizing:border-box"%></td>
    </tr>
    <tr>
      <th>メールアドレス<span class="text-danger">（必須）</span></th>
      <td><%= f.text_field :email ,:style=>"width:80%; box-sizing:border-box"%></td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td><%= f.text_area :message ,:style=>"width:80%; box-sizing:border-box"%></td>
    </tr>
  </table>
  <%= f.submit '確認', class: 'btn btn-primary' %>
<% end %>

app/views/inquiry/thanks.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
<p>
  お問い合わせいただきありがとうございました。
</p>

app/views/interns/_form.html.erb
<%= form_for(@intern) do |f| %>
  <% if @intern.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@intern.errors.count, "error") %> prohibited this intern from being saved:</h2>

      <ul>
      <% @intern.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :context %><br>
    <%= f.text_area :context %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :timeschedule %><br>
    <%= f.text_area :timeschedule %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.text_area :deadline %>
  </div>
  <div class="field">
    <%= f.label :baggage %><br>
    <%= f.text_area :baggage %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "タグ（カンマ区切り）" %><br>
    <%= text_field_tag 'intern[tag_list]', @intern.tag_list.join(',') %>
  </div>
  <div class="field">
    <%= f.label :intern_type %><br>
    <%= f.select :intern_type ,{"その他"=>0,"インターン"=>1,"イベント"=>2,"説明会"=>3}%>
  </div>
  <div class="field">
    <%= f.label :intern_span %><br>
    <%= f.select :intern_span ,{"その他"=>0,"短期インターン"=>1,"長期インターン"=>2}%>
  </div>
  <%= image_tag attachment_url(@intern, :company_image, :fill, 300, 300, format: "jpg" ) %>

  <div class="field">
    <%= f.label :company_image %>
    <%= f.attachment_field :company_image %>
    <%= f.check_box :remove_company_image %>
    <%= f.label :remove_company_image %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interns/edit.html.erb
<h1>Editing Intern</h1>

<%= render 'form' %>

<%= link_to 'Show', @intern %> |
<%= link_to 'Back', interns_path %>

app/views/interns/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 cover-img" style="background-image:url('https://manablog.org/wp-content/uploads/2016/11/top-img.jpg');-moz-background-size:cover;
background-size:cover;">
      <div class="cover-text text-center">
      <p style="height: 200px;"></p>
      <%= image_tag attachment_url(@intern, :company_image, :fill, 300, 300, format: "jpg" ),:class=>'img-thumbnail' %>
      
        <h1 style="color: #fff;">ごのせん</h1>
        <h2 style="color: #fff;">〜九州の学生のための就活情報まとめサイト〜</h2>


        <p style="height: 200px;"></p>
      </div>
    </div>
  </div>
</div>

<h1><CENTER>イベントカレンダー</CENTER></h1>
<div>
  <ul class="nav nav-tabs" role="tablist">
    <li class="active" role="presentation">
      <!--%= link_to "A",interns_path, role:"tab" %-->
      <a aria-controls="tab_a" data-toggle="tab" href="#tab_a" role="tab">すべて</a>
    </li>
    <li role="presentation">
      <a aria-controls="tab_b" data-toggle="tab" href="#tab_b" role="tab">短期インターン</a>
    </li>
    <li role="presentation">
      <a aria-controls="tab_c" data-toggle="tab" href="#tab_c" role="tab">イベント</a>
    </li>
    <li role="presentation">
      <a aria-controls="tab_d" data-toggle="tab" href="#tab_d" role="tab">説明会</a>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab_a" role="tabpanel">
      <%= month_calendar events: @interns , class: "simple-calendar" do |date,interns| %>
        <%= date.day %>
          <% interns.each do |intern| %>
          <div>
            <%= link_to intern.title, intern %>
          </div>
          <% if admin_signed_in?%>
            <%= link_to 'Edit', edit_intern_path(intern),:class=>"btn btn-warning" %>
            <%= link_to 'Destroy', intern, method: :delete, data: { confirm: 'Are you sure?' } ,:class=>"btn btn-danger"%>
          <% end %>
        <% end %>
      <% end %>

    </div>
    <div class="tab-pane" id="tab_b" role="tabpanel">
      <%= month_calendar events: @interns.where(intern_type: 1) , class: "simple-calendar" do |date,interns| %>
        <%= date.day %>
          <% interns.each do |intern| %>
          <div>
            <%= link_to intern.title, intern %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="tab-pane" id="tab_c" role="tabpanel">
      <%= month_calendar events: @interns.where(intern_type: 2)  , class: "simple-calendar" do |date,interns| %>
        <%= date.day %>
          <% interns.each do |intern| %>
          <div>
            <%= link_to intern.title, intern %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="tab-pane" id="tab_d" role="tabpanel">
      <%= month_calendar events: @interns.where(intern_type: 3)  , class: "simple-calendar" do |date,interns| %>
        <%= date.day %>
          <% interns.each do |intern| %>
          <div>
            <%= link_to intern.title, intern %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<br>

<% if admin_signed_in? %>
  <%= link_to 'New Intern', new_intern_path %>
<% end %>

app/views/interns/information.html.erb
<p id="notice"><%= notice %></p>

<h2><CENTER>就職情報</CENTER></h2>
<div class="container">
<div class="row">

<% @tags.each do |tag|%>
    <div class="col-xs-2 col-md-2 text-center">
          <%= link_to  :controller => "interns", :action => "information",:tag => tag.name do%>
            <button class="btn btn-info"><%=tag.name%></button>
          <% end %>
    </div>
<%end%>
<p style="height: 80px;"></p>
  <% @interns.each do |intern|%>
    <div class="col-xs-6 col-md-3">
      <div class="card">

         <div class="card-block">     
                <%=link_to  intern_path(intern) do %>


        <%=image_tag attachment_url(intern, :company_image, :fill, 250, 150, fallback: "default.png", format: "jpg"), :size => "250x150",:class=>"card-img-top",:alt=>"Card image cap" %>  

          <%end%>


          <h4 class="card-title"><%= intern.title%></h4>
        </div>
      </div>
    </div>
  <%end%>
</div>
</div>

app/views/interns/new.html.erb
<h1>New Intern</h1>

<%= render 'form' %>

<%= link_to 'Back', interns_path %>

app/views/interns/overview.html.erb
<p id="notice"><%= notice %></p>

<h2><CENTER>インターンシップ一覧</CENTER></h2>
<div class="container">
<div class="row">

<ul class="nav nav-tabs" role="tablist">
    <li class="active" role="presentation">
      <!--%= link_to "A",interns_path, role:"tab" %-->
      <a aria-controls="tab_a" data-toggle="tab" href="#tab_a" role="tab">短期インターン</a>
    </li>
    <li role="presentation">
      <a aria-controls="tab_b" data-toggle="tab" href="#tab_b" role="tab">長期インターン</a>
    </li>
  </ul>
  <p style="height: 20px;"></p>
  <div class="tab-content">
    <div class="tab-pane active" id="tab_a" role="tabpanel">
        <% @interns.where(intern_span: 1).each do |intern|%>
    <div class="col-xs-6 col-md-3">
      <div class="card">

         <div class="card-block">     
                <%=link_to  intern_path(intern) do %>

        <%=image_tag attachment_url(intern, :company_image, :fill, 250, 150, fallback: "default.png", format: "jpg"), :size => "250x150",:class=>"card-img-top",:alt=>"Card image cap" %>  

          <%end%>


          <h4 class="card-title"><%= intern.title%></h4>
        </div>
      </div>
    </div>
  <%end%>
    </div>
    <div class="tab-pane" id="tab_b" role="tabpanel">
  <% @interns.where(intern_span: 2).each do |intern|%>
    <div class="col-xs-6 col-md-3">
      <div class="card">

         <div class="card-block">     
                <%=link_to  intern_path(intern) do %>

        <%=image_tag attachment_url(intern, :company_image, :fill, 250, 150, fallback: "default.png", format: "jpg"), :size => "250x150",:class=>"card-img-top",:alt=>"Card image cap" %>  

          <%end%>


          <h4 class="card-title"><%= intern.title%></h4>
        </div>
      </div>
    </div>
  <%end%>
    </div>
    </div>

</div>
</div>

app/views/interns/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12 cover-img" style="background-image:url('https://manablog.org/wp-content/uploads/2016/11/top-img.jpg');-moz-background-size:cover;
background-size:cover;">
			<div class="cover-text text-center">
			<p style="height: 150px;"></p>
			<%= image_tag attachment_url(@intern, :company_image, :fill, 300, 300, format: "jpg" ) %>
			
				<h1 style="color: #fff;"><%= simple_format(@intern.title,:style=>"font-size:30px") %></h1>

				<p style="height: 100px;"></p>
			</div>
		</div>
	</div>
</div>


    <div class="container">


      <div class="row text-center">
        <div class="col-md-12">
        <p style="height: 100px;"></p>
        <h2>内容</h2>
        <p style="height: 50px;"></p>
        <h4><%= auto_link(simple_format(@intern.context)) %></h4>
        <p style="height: 200px;"></p>
        <h2>詳細</h2>
        <p style="height: 50px;"></p>

<table class="table table-striped">
  <tbody>
    <tr>
      <th scope="row" width="20%">日時</th>
      <td class="text-left">
      
      <%= @intern.start_time.strftime("%Y年 %m月 %d日")%>
      <%if @intern.start_time.to_date!=@intern.end_time.to_date then%>
      <%= @intern.end_time.strftime("〜%Y年 %m月 %d日")%>
      <%end%>
      </td>
    </tr>
    <tr>
      <th scope="row">場所</th>
      <td class="text-left"><%= auto_link(simple_format(@intern.location))%></td>
    </tr>
    <tr>
      <th scope="row">タイムスケジュール</th>
      <td class="text-left"><%= auto_link(simple_format(@intern.timeschedule))%></td>
    </tr>
    <tr>
      <th scope="row">応募方法・締め切り</th>
      <td class="text-left"><%= auto_link(simple_format(@intern.deadline))%></td>
    </tr>   
    <tr>
      <th scope="row">持ち物・服装</th>
      <td class="text-left"><%= auto_link(simple_format(@intern.baggage))%></td>
    </tr>   
    <tr>
      <th scope="row">主催</th>
      <td class="text-left"><%= auto_link(simple_format(@intern.owner))%></td>
    </tr>   

  </tbody>
</table>

</div>

    </div> <!-- /container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gonosen</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'login', media: 'all', 'data-turbolinks-track' => false %>
  <%= stylesheet_link_tag    'simple-calendar', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    "bootstrap.min" %>
  <%= javascript_include_tag "bootstrap.min" %>
  <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/img/favicon.png">
	<link href='http://fonts.googleapis.com/css?family=Lato:300,400,900' rel='stylesheet' type='text/css'>

    <%= analytics_init if Rails.env.production? %>

</head>
<body>
    <header>
    <nav class="navbar navbar-fixed-top navbar-light bg-faded navbar-inverse">
      <%= link_to "ごのせん",interns_path, :class=>"navbar-brand" %>
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <%= link_to "Home",interns_path, :class=>"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "インターン",overview_interns_path, :class=>"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "就活情報",information_interns_path, :class=>"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "お問い合わせ",inquiry_path, :class=>"nav-link" %>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
             
      <% if admin_signed_in? %> 
      Logged in as <strong><%= current_admin.email %></strong>.
      <li class="nav-item"> 
      <%= link_to 'プロフィール変更', edit_admin_registration_path %>
      </li>
      <li class="nav-item"> 
      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
      </li>
      <% else %>
      <li class="nav-item"> 
        <%= link_to "ログイン", new_admin_session_path %>
        </li>
      <% end %>
      </ul>


    </nav>
    </header>
    <p style="height: 40px;"></p>
<%= yield %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <CENTER>
    Copyright ⓒ 防人PJ.All Rights Reserved
  </CENTER>
  </div>
</nav>
</body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>